version: "3.7"
services:
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: basics
      MYSQL_USER: ivi_user
      MYSQL_PASSWORD: ivi_password
      MYSQL_ROOT_PASSWORD: ivi_password